// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Application.Misiones.Proyecciones.BorradorIA", b =>
                {
                    b.Property<Guid>("MisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("uuid")
                        .HasColumnName("aula_id");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("docente_id");

                    b.Property<string>("EstadoValidacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_validacion");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text")
                        .HasColumnName("motivo_rechazo");

                    b.Property<string>("Narrativa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("narrativa");

                    b.Property<int>("NivelConfianzaIA")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_confianza_ia");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("RecompensaXpSugerida")
                        .HasColumnType("integer")
                        .HasColumnName("recompensa_xp_sugerida");

                    b.Property<string>("TemaCurricular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tema_curricular");

                    b.Property<string>("TipoPlantilla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_plantilla");

                    b.HasKey("MisionId")
                        .HasName("pk_borradores_ia");

                    b.ToTable("borradores_ia", (string)null);
                });

            modelBuilder.Entity("Core.Application.Misiones.Proyecciones.MisionActiva", b =>
                {
                    b.Property<Guid>("MisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("uuid")
                        .HasColumnName("aula_id");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("docente_id");

                    b.Property<string>("Narrativa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("narrativa");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("RecompensaXp")
                        .HasColumnType("integer")
                        .HasColumnName("recompensa_xp");

                    b.Property<string>("TipoPlantilla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_plantilla");

                    b.HasKey("MisionId")
                        .HasName("pk_misiones_activas");

                    b.ToTable("misiones_activas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entidades.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoInvitacion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("codigo_invitacion");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("docente_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_aulas");

                    b.HasIndex("CodigoInvitacion")
                        .IsUnique()
                        .HasDatabaseName("ix_aulas_codigo_invitacion");

                    b.HasIndex("DocenteId")
                        .HasDatabaseName("ix_aulas_docente_id");

                    b.ToTable("aulas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entidades.Inscripcion", b =>
                {
                    b.Property<Guid>("AulaId")
                        .HasColumnType("uuid")
                        .HasColumnName("aula_id");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid")
                        .HasColumnName("alumno_id");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inscripcion");

                    b.HasKey("AulaId", "AlumnoId")
                        .HasName("pk_inscripciones");

                    b.HasIndex("AlumnoId")
                        .HasDatabaseName("ix_inscripciones_alumno_id");

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entidades.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmailTutor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email_tutor");

                    b.Property<string>("EstadoCuenta")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("estado_cuenta");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_rol_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Infrastructure.EventStore.EventoPersistido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<DateTime>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("TipoAgregado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_agregado");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tipo_evento");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_eventos_almacenados");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_eventos_almacenados_aggregate_id_version");

                    b.ToTable("eventos_almacenados", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entidades.Aula", b =>
                {
                    b.HasOne("Core.Domain.Entidades.Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aulas_usuarios_docente_id");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Core.Domain.Entidades.Inscripcion", b =>
                {
                    b.HasOne("Core.Domain.Entidades.Usuario", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inscripciones_usuarios_alumno_id");

                    b.HasOne("Core.Domain.Entidades.Aula", "Aula")
                        .WithMany("Inscripciones")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inscripciones_aulas_aula_id");

                    b.Navigation("Alumno");

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("Core.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("Core.Domain.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_rol_id");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Core.Domain.Entidades.Aula", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
